### ISSUE TITLE
Adding to Groups/Lists instead adds to the top layer

### ISSUE THREAD

**Issue by OddHero** [FazziCLAY/OpenToday#25] opened 2023-02-25 14:15 UTC
Expected: pressing (+) > new item appears inside the open group.
Actual behaviour: pressing (+) > Item appears at top level.

Extra info: The blue (!) Does add to the opened group but does not open the options of the new entry...

**Comment by FazziCLAY** [comment] 2023-02-26 08:09
The first is a bug, I do not know how to fix it, but you are right.

The second is a trick.
The + button adds and opens parameters
The button ! adds and that's it (for a large number of additions)

**Comment by FazziCLAY** [comment] 2023-02-26 08:10
duplicate of #10

**Comment by FazziCLAY** [comment] 2023-02-26 08:14
**as a temporary solution: log out and log in again several times to the desired group, after items will begin to be added to it**

**Comment by FazziCLAY** [comment] 2023-03-02 15:34
fixed

**Closed by FazziCLAY** 2023-03-02 15:34 UTC
Labels: bug, duplicate, allow-to-fix
